# Generated by Django 5.1.2 on 2025-01-14 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_deliveryprocedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprocedure',
            name='procedure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_procedures', to='core.requestprocedure'),
        ),
    ]
