# Generated by Django 5.1.2 on 2025-06-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, null=True, verbose_name='No. Celular'),
        ),
    ]
