# Generated by Django 5.1.2 on 2025-11-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0006_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cargo o Posición:'),
        ),
    ]
