# Generated by Django 5.1.2 on 2024-12-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_accounting_subgroup_alter_infosubgroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Titulo'),
        ),
    ]
