# Generated by Django 5.1.2 on 2025-01-24 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_categorytransparency_transparency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependenceTransparency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(verbose_name='Nombre de la Dependencia')),
            ],
        ),
        migrations.AlterField(
            model_name='transparency',
            name='dependence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.dependencetransparency', verbose_name='Dependence'),
        ),
    ]
