# Generated by Django 5.1.2 on 2024-12-29 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("website", "0009_alter_gazette_document_alter_gazette_month_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="citizen",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Primer apellido"),
                ),
                (
                    "second_name",
                    models.CharField(max_length=50, verbose_name="Segundo apellido"),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Dirección")),
                (
                    "cellphone",
                    models.CharField(
                        blank=True, null=True, unique=True, verbose_name="Celular"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Correo electrónico",
                    ),
                ),
                (
                    "INE",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="INE"
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Fecha de nacimiento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcedureType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
            ],
        ),
        migrations.CreateModel(
            name="RequestProcedure",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "description",
                    models.CharField(
                        max_length=200, verbose_name="Descripción de la Solicitud"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/requests_procedures/",
                        verbose_name="Documento",
                    ),
                ),
                ("creation", models.DateTimeField(auto_now=True)),
                (
                    "capturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_capturer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "procedure_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedures_types",
                        to="core.proceduretype",
                        verbose_name="Tipo de gestion",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requesters",
                        to="core.citizen",
                        verbose_name="Solicitante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackingProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folio",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Folio del documento",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/tracking_procedures/",
                        verbose_name="Documento",
                    ),
                ),
                ("remarks", models.TextField(verbose_name="Observaciones")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Autorizada", "Autorizada"),
                            ("Entregada", "Entregada"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="Pendiente",
                        max_length=20,
                        verbose_name="Estado de la solicitud",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "Procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.requestprocedure",
                    ),
                ),
                (
                    "capturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_capturer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_department",
                        to="website.dependence",
                        verbose_name="Departamento que recibe",
                    ),
                ),
                (
                    "to_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_department",
                        to="website.dependence",
                        verbose_name="Departamento que emite",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
