# Generated by Django 5.1.2 on 2025-01-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_commentprocedure"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentprocedure",
            name="comment",
            field=models.TextField(default="Sin comentario", verbose_name="comentario"),
            preserve_default=False,
        ),
    ]
