# Generated by Django 5.1.2 on 2025-01-14 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_documenttypeprocedure_alter_commentprocedure_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentprocedure",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents_types_procedures",
                to="core.documenttypeprocedure",
                verbose_name="Tipo de documento",
            ),
        ),
    ]
