# Generated by Django 5.1.2 on 2025-03-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_requestprocedure_current_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Departamento"
            ),
        ),
        migrations.AlterField(
            model_name="dependence",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Dependencia"
            ),
        ),
        migrations.AlterField(
            model_name="director",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="images/NoPhoto.png",
                null=True,
                upload_to="images/townhall/directors_profiles/",
                verbose_name="Imagen de perfil",
            ),
        ),
    ]
