# Generated by Django 5.1.2 on 2025-04-19 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_department_name_alter_dependence_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependence',
            name='director',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_dependence', to='core.director'),
        ),
    ]
