# Generated by Django 5.1.2 on 2025-04-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_dependence_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dependence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_departments', to='core.dependence'),
        ),
    ]
