# Generated by Django 5.1.2 on 2024-12-22 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0009_alter_gazette_document_alter_gazette_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='citizen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('second_name', models.CharField(max_length=50, verbose_name='Segundo apellido')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('cellphone', models.IntegerField(max_length=10, null=True, unique=True, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Correo electrónico')),
                ('INE', models.CharField(blank=True, max_length=20, null=True, verbose_name='INE')),
                ('birthdate', models.DateField(blank=True, max_length=20, null=True, verbose_name='Fecha de nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request', models.CharField(max_length=200, verbose_name='Solicitud')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/request/', verbose_name='Documento')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atorizada', 'Autorizada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20, verbose_name='Estado de la solicitud')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dependence', to='website.dependence')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='procedures.citizen')),
            ],
        ),
    ]
