# Generated by Django 5.1.2 on 2024-12-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='cellphone',
            field=models.IntegerField(null=True, unique=True, verbose_name='Celular'),
        ),
    ]
