# Generated by Django 5.1.2 on 2024-12-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0002_alter_citizen_cellphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='request',
            name='direction',
        ),
        migrations.DeleteModel(
            name='citizen',
        ),
        migrations.DeleteModel(
            name='request',
        ),
    ]
