# Generated by Django 5.1.2 on 2024-12-16 19:42

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_chat", "0008_chatanonymous_useranonymous_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anonymousmessage",
            name="author",
        ),
        migrations.RemoveField(
            model_name="anonymousmessage",
            name="group",
        ),
        migrations.AlterField(
            model_name="chatgroup",
            name="group_name",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="UserAnonymous",
        ),
        migrations.DeleteModel(
            name="AnonymousMessage",
        ),
        migrations.DeleteModel(
            name="ChatAnonymous",
        ),
    ]
