# Generated by Django 5.1.2 on 2025-05-15 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del atributo')),
                ('type', models.CharField(choices=[('P', 'Percepción'), ('D', 'Deducción')], max_length=1, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Banco:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Regimen fiscal:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
        ),
        migrations.CreateModel(
            name='TypeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Tipo de salario:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Jornada:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
        ),
        migrations.CreateModel(
            name='Dependence',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='Ramo:')),
                ('name', models.CharField(unique=True, verbose_name='Dirección:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve_empleado')),
                ('paternal_surname', models.CharField(blank=True, null=True, verbose_name='Apellido paterno:')),
                ('maternal_surname', models.CharField(blank=True, null=True, verbose_name='Apellido materno:')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Nombre:')),
                ('rfc', models.CharField(blank=True, null=True, verbose_name='RFC:')),
                ('curp', models.CharField(blank=True, null=True, verbose_name='CURP:')),
                ('base_date', models.CharField(blank=True, null=True, verbose_name='Fecha de base:')),
                ('contract_date', models.CharField(blank=True, null=True, verbose_name='Fecha de contrato:')),
                ('nss', models.CharField(blank=True, null=True, verbose_name='NSS:')),
                ('cp', models.CharField(blank=True, null=True, verbose_name='Código postal:')),
                ('birth_date', models.CharField(blank=True, null=True, verbose_name='Fecha de nacimiento:')),
                ('sex', models.CharField(blank=True, null=True, verbose_name='Sexo:')),
                ('account_no', models.CharField(blank=True, null=True, verbose_name='Número de cuenta:')),
                ('bank', models.CharField(blank=True, null=True, verbose_name='Banco:')),
                ('working_day', models.CharField(blank=True, null=True, verbose_name='Jornada:')),
                ('type_salary', models.CharField(blank=True, null=True, verbose_name='Tipo de salario:')),
                ('tax_regime', models.CharField(blank=True, null=True, verbose_name='Régimen fiscal:')),
                ('qna', models.CharField(blank=True, null=True, verbose_name='QNA:')),
                ('period', models.CharField(blank=True, null=True, verbose_name='Periodo:')),
                ('text_dependence', models.CharField(blank=True, null=True, verbose_name='Departamento:')),
                ('text_position', models.CharField(blank=True, null=True, verbose_name='Puesto:')),
                ('paid_days', models.CharField(blank=True, null=True, verbose_name='Dias pagados:')),
                ('dependence', models.CharField(blank=True, null=True, verbose_name='Ramo:')),
                ('position', models.CharField(blank=True, null=True, verbose_name='cve_pto:')),
                ('type_employee', models.CharField(blank=True, null=True, verbose_name='sindicato:')),
                ('type_payroll', models.CharField(blank=True, null=True, verbose_name='nomina:')),
                ('type', models.CharField(blank=True, null=True, verbose_name='Tipo')),
                ('total_salary', models.CharField(blank=True, null=True, verbose_name='Total neto:')),
                ('entry_date', models.CharField(blank=True, null=True, verbose_name='Fecha de alta:')),
                ('movement', models.CharField(blank=True, null=True, verbose_name='cve Cambio')),
                ('change', models.CharField(blank=True, null=True, verbose_name='Cambio')),
                ('age', models.CharField(blank=True, null=True, verbose_name='Edad')),
                ('seniority', models.CharField(blank=True, null=True, verbose_name='Antiguedad laboral')),
                ('commission', models.CharField(blank=True, null=True, verbose_name='Comision:')),
                ('location', models.CharField(blank=True, null=True, verbose_name='Ubicación:')),
                ('responsibility', models.CharField(blank=True, null=True, verbose_name='Función:')),
                ('address', models.CharField(blank=True, null=True, verbose_name='Dirección')),
                ('colony', models.CharField(blank=True, null=True, verbose_name='Colonia:')),
                ('locality', models.CharField(blank=True, null=True, verbose_name='Municipio:')),
                ('state', models.CharField(blank=True, null=True, verbose_name='Estado:')),
                ('place_birth', models.CharField(blank=True, null=True, verbose_name='Lugar de nacimiento:')),
                ('email', models.CharField(blank=True, null=True, verbose_name='Correo electrónico:')),
                ('phone', models.CharField(blank=True, null=True, verbose_name='Teléfono:')),
                ('leaving_date', models.CharField(blank=True, null=True, verbose_name='Fecha de baja:')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Nota:')),
            ],
            options={
                'indexes': [models.Index(fields=['key'], name='a_payroll_e_key_24009d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='Clave de empleado:')),
                ('paternal_surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido paterno:')),
                ('maternal_surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno:')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre:')),
                ('status', models.BooleanField(blank=True, choices=[(True, 'ACTIVO'), (False, 'INACTIVO')], default=True, null=True, verbose_name='Estatus del empleado:')),
            ],
            options={
                'indexes': [models.Index(fields=['key'], name='a_payroll_e_key_b9bf23_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.attributecatalog')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='a_payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellphone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular:')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono:')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico:')),
                ('country', models.CharField(blank=True, null=True, verbose_name='Pais:')),
                ('state', models.CharField(blank=True, null=True, verbose_name='Estado:')),
                ('municipality', models.CharField(blank=True, null=True, verbose_name='Municipio:')),
                ('postal_code', models.CharField(blank=True, null=True, verbose_name='Código postal:')),
                ('colony', models.CharField(blank=True, null=True, verbose_name='Colonia:')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Calle:')),
                ('no_ext', models.CharField(blank=True, max_length=10, null=True, verbose_name='No.Ext:')),
                ('no_int', models.CharField(blank=True, max_length=10, null=True, verbose_name='No.Int:')),
                ('reference', models.CharField(blank=True, null=True, verbose_name='Referencia:')),
                ('languages', models.TextField(blank=True, null=True, verbose_name='Idiomas:')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento:')),
                ('sex', models.CharField(blank=True, choices=[('F', 'FEMENINO'), ('M', 'MASCULINO')], null=True, verbose_name='Sexo:')),
                ('marital_status', models.CharField(blank=True, choices=[('SOLTERO', 'SOLTERO'), ('CASADO', 'CASADO'), ('DIVORCIADO', 'DIVORCIADO'), ('VIUDO', 'VIUDO')], null=True, verbose_name='Estado civil:')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_information', to='a_payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve')),
                ('name', models.CharField(unique=True, verbose_name='Movimiento:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio del periodo:')),
                ('end_date', models.DateField(verbose_name='Fecha de fin del periodo:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'ordering': ['start_date'],
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('perception_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deduction_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('generation_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_payroll.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_payroll.period')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve')),
                ('name', models.CharField(unique=True, verbose_name='Puesto:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeTaxData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(blank=True, null=True, verbose_name='RFC:')),
                ('curp', models.CharField(blank=True, null=True, verbose_name='CURP:')),
                ('nss', models.CharField(blank=True, null=True, verbose_name='NSS:')),
                ('cp', models.CharField(blank=True, null=True, verbose_name='Código postal:')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_information', to='a_payroll.employee')),
                ('tax_regime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.taxregime', verbose_name='Régimen fiscal:')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve')),
                ('name', models.CharField(unique=True, verbose_name='Tipo:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TypeEmployee',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve')),
                ('name', models.CharField(unique=True, verbose_name='Tipo de empleado:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TypePayroll',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve')),
                ('name', models.CharField(unique=True, verbose_name='Tipo de nomina:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CategoryTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.position', verbose_name='Puesto:')),
                ('type_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typeemployee', verbose_name='Tipo de empleado:')),
                ('type_payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typepayroll', verbose_name='Tipo de nómina:')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeJobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Salario total:')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta:')),
                ('base_date', models.DateField(blank=True, null=True, verbose_name='Fecha de base:')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Fecha de contrato:')),
                ('contract_termination_date', models.DateField(blank=True, null=True, verbose_name='Fecha de termino de contrato:')),
                ('account_no', models.BigIntegerField(blank=True, null=True, verbose_name='Número de cuenta:')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Hora de salida:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del puesto:')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.bank', verbose_name='Banco:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_category', to='a_payroll.categorytab')),
                ('dependence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.dependence', verbose_name='Departamento:')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_information', to='a_payroll.employee')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.movement', verbose_name='Cambio')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.position', verbose_name='Puesto:')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.type', verbose_name='Tipo')),
                ('type_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typeemployee', verbose_name='Tipo de empleado:')),
                ('type_payroll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typepayroll', verbose_name='Tipo de nómina:')),
                ('type_salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typesalary', verbose_name='Tipo de salario:')),
                ('working_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.workingday', verbose_name='Jornada:')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='a_payroll.attributecatalog')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='a_payroll.categorytab')),
            ],
            options={
                'ordering': ('attribute__type', 'attribute__name'),
                'indexes': [models.Index(fields=['category'], name='a_payroll_c_categor_bdfabd_idx')],
                'unique_together': {('category', 'attribute')},
            },
        ),
        migrations.AddIndex(
            model_name='categorytab',
            index=models.Index(fields=['position', 'type_employee', 'type_payroll'], name='a_payroll_c_positio_a32f1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categorytab',
            unique_together={('position', 'type_employee', 'type_payroll')},
        ),
    ]
