# Generated by Django 5.1.2 on 2025-04-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve')),
                ('name', models.CharField(unique=True, verbose_name='Dirección:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Dependence',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='Ramo:')),
                ('name', models.CharField(unique=True, verbose_name='Dirección:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve')),
                ('name', models.CharField(unique=True, verbose_name='Movimiento:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve')),
                ('name', models.CharField(unique=True, verbose_name='Tipo:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TypeEmployee',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve')),
                ('name', models.CharField(unique=True, verbose_name='Tipo de empleado:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TypePayroll',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve')),
                ('name', models.CharField(unique=True, verbose_name='Tipo de nomina:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
    ]
