# Generated by Django 5.1.2 on 2025-06-13 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='Banco:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del atributo')),
                ('type', models.CharField(choices=[('P', 'Percepción'), ('D', 'Deducción')], max_length=1, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRegime',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='Regimen fiscal:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
        ),
        migrations.CreateModel(
            name='TypeSalary',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='Tipo de salario:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='Jornada:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
        ),
        migrations.CreateModel(
            name='Dependence',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='Ramo:')),
                ('name', models.CharField(unique=True, verbose_name='Dirección:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve_empleado')),
                ('paternal_surname', models.CharField(blank=True, null=True, verbose_name='Apellido paterno:')),
                ('maternal_surname', models.CharField(blank=True, null=True, verbose_name='Apellido materno:')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Nombre:')),
                ('rfc', models.CharField(blank=True, null=True, verbose_name='RFC:')),
                ('curp', models.CharField(blank=True, null=True, verbose_name='CURP:')),
                ('base_date', models.CharField(blank=True, null=True, verbose_name='Fecha de base:')),
                ('contract_date', models.CharField(blank=True, null=True, verbose_name='Fecha de contrato:')),
                ('nss', models.CharField(blank=True, null=True, verbose_name='NSS:')),
                ('cp', models.CharField(blank=True, null=True, verbose_name='Código postal:')),
                ('birth_date', models.CharField(blank=True, null=True, verbose_name='Fecha de nacimiento:')),
                ('sex', models.CharField(blank=True, null=True, verbose_name='Sexo:')),
                ('account_no', models.CharField(blank=True, null=True, verbose_name='Número de cuenta:')),
                ('bank', models.CharField(blank=True, null=True, verbose_name='Banco:')),
                ('working_day', models.CharField(blank=True, null=True, verbose_name='Jornada:')),
                ('type_salary', models.CharField(blank=True, null=True, verbose_name='Tipo de salario:')),
                ('tax_regime', models.CharField(blank=True, null=True, verbose_name='Régimen fiscal:')),
                ('qna', models.CharField(blank=True, null=True, verbose_name='QNA:')),
                ('period', models.CharField(blank=True, null=True, verbose_name='Periodo:')),
                ('text_dependence', models.CharField(blank=True, null=True, verbose_name='Departamento:')),
                ('text_position', models.CharField(blank=True, null=True, verbose_name='Puesto:')),
                ('paid_days', models.CharField(blank=True, null=True, verbose_name='Dias pagados:')),
                ('dependence', models.CharField(blank=True, null=True, verbose_name='Ramo:')),
                ('position', models.CharField(blank=True, null=True, verbose_name='cve_pto:')),
                ('type_employee', models.CharField(blank=True, null=True, verbose_name='sindicato:')),
                ('type_payroll', models.CharField(blank=True, null=True, verbose_name='nomina:')),
                ('type', models.CharField(blank=True, null=True, verbose_name='Tipo')),
                ('salary', models.CharField(blank=True, null=True, verbose_name='Sueldo:')),
                ('perception', models.CharField(blank=True, null=True, verbose_name='Percepciones:')),
                ('deduction', models.CharField(blank=True, null=True, verbose_name='Deducciones:')),
                ('net_total', models.CharField(blank=True, null=True, verbose_name='Total neto:')),
                ('entry_date', models.CharField(blank=True, null=True, verbose_name='Fecha de alta:')),
                ('cve_change', models.CharField(blank=True, null=True, verbose_name='cve Cambio')),
                ('text_change', models.CharField(blank=True, null=True, verbose_name='Cambio')),
                ('age', models.CharField(blank=True, null=True, verbose_name='Edad')),
                ('seniority', models.CharField(blank=True, null=True, verbose_name='Antiguedad laboral')),
                ('commission', models.CharField(blank=True, null=True, verbose_name='Comision:')),
                ('location', models.CharField(blank=True, null=True, verbose_name='Ubicación:')),
                ('responsibility', models.CharField(blank=True, null=True, verbose_name='Función:')),
                ('address', models.CharField(blank=True, null=True, verbose_name='Dirección')),
                ('colony', models.CharField(blank=True, null=True, verbose_name='Colonia:')),
                ('locality', models.CharField(blank=True, null=True, verbose_name='Localidad:')),
                ('municipality', models.CharField(blank=True, null=True, verbose_name='Municipio:')),
                ('state', models.CharField(blank=True, null=True, verbose_name='Estado:')),
                ('place_birth', models.CharField(blank=True, null=True, verbose_name='Lugar de nacimiento:')),
                ('email', models.CharField(blank=True, null=True, verbose_name='Correo electrónico:')),
                ('phone', models.CharField(blank=True, null=True, verbose_name='Teléfono:')),
                ('leaving_date', models.CharField(blank=True, null=True, verbose_name='Fecha de baja:')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Nota:')),
            ],
            options={
                'indexes': [models.Index(fields=['key'], name='a_payroll_e_key_24009d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='Clave de empleado:')),
                ('paternal_surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido paterno:')),
                ('maternal_surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno:')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre:')),
                ('rfc', models.CharField(blank=True, null=True, verbose_name='RFC:')),
                ('curp', models.CharField(blank=True, null=True, verbose_name='CURP:')),
                ('base_date', models.DateField(blank=True, null=True, verbose_name='Fecha de base:')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Fecha de contrato:')),
                ('nss', models.CharField(blank=True, null=True, verbose_name='NSS:')),
                ('cp', models.CharField(blank=True, null=True, verbose_name='Código postal:')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento:')),
                ('sex', models.CharField(blank=True, choices=[('F', 'FEMENINO'), ('M', 'MASCULINO')], null=True, verbose_name='Sexo:')),
                ('account_no', models.BigIntegerField(blank=True, null=True, verbose_name='Número de cuenta:')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta:')),
                ('commission', models.CharField(blank=True, null=True, verbose_name='Comision:')),
                ('location', models.CharField(blank=True, null=True, verbose_name='Ubicación:')),
                ('function', models.CharField(blank=True, null=True, verbose_name='Función:')),
                ('address', models.CharField(blank=True, null=True, verbose_name='Dirección')),
                ('colony', models.CharField(blank=True, null=True, verbose_name='Colonia:')),
                ('locality', models.CharField(blank=True, null=True, verbose_name='Localidad:')),
                ('municipality', models.CharField(blank=True, null=True, verbose_name='Municipio:')),
                ('state', models.CharField(blank=True, null=True, verbose_name='Estado:')),
                ('place_birth', models.CharField(blank=True, null=True, verbose_name='Lugar de nacimiento:')),
                ('email', models.CharField(blank=True, null=True, verbose_name='Correo electrónico:')),
                ('phone', models.CharField(blank=True, null=True, verbose_name='Teléfono:')),
                ('leaving_date', models.DateField(blank=True, null=True, verbose_name='Fecha de baja:')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Nota:')),
                ('status', models.BooleanField(blank=True, choices=[(True, 'ACTIVO'), (False, 'INACTIVO')], default=True, null=True, verbose_name='Estatus del empleado:')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.bank', verbose_name='Banco:')),
                ('dependence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.dependence', verbose_name='Departamento:')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.concept')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='a_payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve')),
                ('name', models.CharField(unique=True, verbose_name='Movimiento:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.movement', verbose_name='Cambio'),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio del periodo:')),
                ('end_date', models.DateField(verbose_name='Fecha de fin del periodo:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'ordering': ['start_date'],
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve')),
                ('name', models.CharField(unique=True, verbose_name='Puesto:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.position', verbose_name='Puesto:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_regime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.taxregime', verbose_name='Régimen fiscal:'),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve')),
                ('name', models.CharField(unique=True, verbose_name='Tipo:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.type', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='TypeEmployee',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve')),
                ('name', models.CharField(unique=True, verbose_name='Tipo de empleado:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='type_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typeemployee', verbose_name='Tipo de empleado:'),
        ),
        migrations.CreateModel(
            name='TypePayroll',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve')),
                ('name', models.CharField(unique=True, verbose_name='Tipo de nomina:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='type_payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typepayroll', verbose_name='Tipo de nómina:'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.position', verbose_name='Puesto:')),
                ('type_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typeemployee', verbose_name='Tipo de empleado:')),
                ('type_payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typepayroll', verbose_name='Tipo de nómina:')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='type_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typesalary', verbose_name='Tipo de salario:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='workday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.workday', verbose_name='Jornada:'),
        ),
        migrations.CreateModel(
            name='CategoryConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='a_payroll.category')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='a_payroll.concept')),
            ],
            options={
                'ordering': ('concept__type', 'concept__name'),
                'indexes': [models.Index(fields=['category'], name='a_payroll_c_categor_192d25_idx')],
                'unique_together': {('category', 'concept')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='a_payroll.category')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_category', to='a_payroll.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'category'), name='unique_employee_category')],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['position', 'type_employee', 'type_payroll'], name='a_payroll_c_positio_850a4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('position', 'type_employee', 'type_payroll'), name='unique_category'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['key'], name='a_payroll_e_key_b9bf23_idx'),
        ),
    ]
