# Generated by Django 5.1.2 on 2025-04-23 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Banco:')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Regimen fiscal:')),
            ],
        ),
        migrations.CreateModel(
            name='TypeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Tipo de salario:')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Jornada:')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve_empleado')),
                ('paternal_surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido paterno:')),
                ('maternal_surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno:')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre:')),
                ('rfc', models.CharField(blank=True, null=True, verbose_name='RFC:')),
                ('curp', models.CharField(blank=True, null=True, verbose_name='CURP:')),
                ('base_date', models.DateTimeField(blank=True, null=True)),
                ('contract_date', models.DateTimeField(blank=True, null=True)),
                ('nss', models.CharField(blank=True, null=True, verbose_name='NSS:')),
                ('cp', models.CharField(blank=True, null=True, verbose_name='Código postal:')),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('F', 'F'), ('M', 'M')], null=True, verbose_name='Sexo:')),
                ('account_no', models.BigIntegerField(blank=True, null=True, verbose_name='Número de cuenta:')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.bank', verbose_name='Banco:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.category', verbose_name='Puesto:')),
                ('dependence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.dependence', verbose_name='Departamento:')),
                ('type_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typeemployee', verbose_name='Tipo de empleado:')),
                ('type_payroll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typepayroll', verbose_name='Tipo de nómina:')),
                ('tax_regime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.taxregime', verbose_name='Régimen fiscal:')),
                ('type_salary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typesalary', verbose_name='Tipo de salario:')),
                ('working_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.workingday', verbose_name='Jornada:')),
            ],
        ),
    ]
