# Generated by Django 5.1.2 on 2025-05-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeductionCatalog',
        ),
        migrations.DeleteModel(
            name='PerceptionCatalog',
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', null=True, verbose_name='Estado del empleado:'),
        ),
    ]
