# Generated by Django 5.1.2 on 2025-05-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='movement',
            new_name='cve_change',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='change',
            new_name='text_change',
        ),
        migrations.AddField(
            model_name='empleado',
            name='municipality',
            field=models.CharField(blank=True, null=True, verbose_name='Municipio:'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='locality',
            field=models.CharField(blank=True, null=True, verbose_name='Localidad:'),
        ),
    ]
