# Generated by Django 5.1.2 on 2025-06-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0002_rename_seniority_empleado_antiguedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account_no',
            field=models.CharField(blank=True, null=True, verbose_name='Número de cuenta:'),
        ),
    ]
