# Generated by Django 5.1.2 on 2025-05-06 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0002_delete_deductioncatalog_delete_perceptioncatalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentdata',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_information', to='a_payroll.employee'),
        ),
    ]
