# Generated by Django 5.1.2 on 2025-05-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0002_rename_movement_empleado_cve_change_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorytab',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='categorytab',
            constraint=models.UniqueConstraint(fields=('position', 'type_employee', 'type_payroll'), name='unique_category'),
        ),
    ]
