# Generated by Django 5.1.2 on 2025-04-23 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0002_bank_taxregime_typesalary_workingday_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.bank', verbose_name='Banco:'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.category', verbose_name='Puesto:'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dependence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.dependence', verbose_name='Departamento:'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_regime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.taxregime', verbose_name='Régimen fiscal:'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typeemployee', verbose_name='Tipo de empleado:'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type_payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typepayroll', verbose_name='Tipo de nómina:'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typesalary', verbose_name='Tipo de salario:'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='working_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.workingday', verbose_name='Jornada:'),
        ),
    ]
