# Generated by Django 5.1.2 on 2025-07-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0003_alter_employee_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoryconcept',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='concept',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
