# Generated by Django 5.1.2 on 2025-04-29 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0003_alter_employee_bank_alter_employee_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Nombre de la deducción:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
        ),
        migrations.CreateModel(
            name='PerceptionCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Nombre de la percepción:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='cp',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='base_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='category',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contract_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dependence',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nss',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='rfc',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tax_regime',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='type_employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='type_payroll',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='type_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='working_day',
        ),
        migrations.AddField(
            model_name='bank',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción:'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción:'),
        ),
        migrations.AddField(
            model_name='dependence',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cellphone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='colony',
            field=models.CharField(blank=True, null=True, verbose_name='Colonia:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, null=True, verbose_name='Pais:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='languages',
            field=models.TextField(blank=True, null=True, verbose_name='Idiomas:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'SOLTERO'), ('CASADO', 'CASADO'), ('DIVORCIADO', 'DIVORCIADO'), ('VIUDO', 'VIUDO')], null=True, verbose_name='Estado civil:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='municipality',
            field=models.CharField(blank=True, null=True, verbose_name='Municipio:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='no_ext',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='No.Ext:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='no_int',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='No.Int:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='reference',
            field=models.CharField(blank=True, null=True, verbose_name='Referencia:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, null=True, verbose_name='Estado:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], null=True, verbose_name='Estado del empleado:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Calle:'),
        ),
        migrations.AddField(
            model_name='movement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción:'),
        ),
        migrations.AddField(
            model_name='taxregime',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción:'),
        ),
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción:'),
        ),
        migrations.AddField(
            model_name='typeemployee',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción:'),
        ),
        migrations.AddField(
            model_name='typepayroll',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción:'),
        ),
        migrations.AddField(
            model_name='typesalary',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción:'),
        ),
        migrations.AddField(
            model_name='workingday',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción:'),
        ),
        migrations.CreateModel(
            name='EmployeeTaxtData',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tax_information', serialize=False, to='a_payroll.employee')),
                ('rfc', models.CharField(blank=True, null=True, verbose_name='RFC:')),
                ('curp', models.CharField(blank=True, null=True, verbose_name='CURP:')),
                ('nss', models.CharField(blank=True, null=True, verbose_name='NSS:')),
                ('cp', models.CharField(blank=True, null=True, verbose_name='Código postal:')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento:')),
                ('tax_regime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.taxregime', verbose_name='Régimen fiscal:')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentData',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employment_information', serialize=False, to='a_payroll.employee')),
                ('base_date', models.DateField(blank=True, null=True, verbose_name='Fecha de base:')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Fecha de contrato:')),
                ('contract_termination_date', models.DateField(blank=True, null=True, verbose_name='Fecha de termino de contrato:')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Salario:')),
                ('account_no', models.BigIntegerField(blank=True, null=True, verbose_name='Número de cuenta:')),
                ('chek_in_time', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada')),
                ('chek_out_time', models.TimeField(blank=True, null=True, verbose_name='Hora de salida:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del puesto:')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.bank', verbose_name='Banco:')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.category', verbose_name='Puesto:')),
                ('dependence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.dependence', verbose_name='Departamento:')),
                ('type_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typeemployee', verbose_name='Tipo de empleado:')),
                ('type_payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typepayroll', verbose_name='Tipo de nómina:')),
                ('type_salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typesalary', verbose_name='Tipo de salario:')),
                ('working_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.workingday', verbose_name='Jornada:')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_date', models.DateTimeField(auto_now_add=True)),
                ('perception_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deduction_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_payroll.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_payroll.period')),
            ],
        ),
        migrations.CreateModel(
            name='TestPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perception_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deduction_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.deductioncatalog', verbose_name='Deducción:')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.employee', verbose_name='Empleado:')),
                ('perception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.perceptioncatalog', verbose_name='Percepción:')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_payroll.period')),
                ('type_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typeemployee', verbose_name='Tipo de empleado:')),
                ('type_payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typepayroll', verbose_name='Tipo de nómina:')),
            ],
        ),
        migrations.CreateModel(
            name='BiweeklySalarySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Salario:')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.category', verbose_name='Puesto:')),
                ('type_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typeemployee', verbose_name='Tipo de empleado:')),
                ('type_payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typepayroll', verbose_name='Tipo de nómina:')),
            ],
            options={
                'unique_together': {('category', 'type_employee', 'type_payroll')},
            },
        ),
        migrations.CreateModel(
            name='BiweeklyDeductionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor de la Deducción:')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.category', verbose_name='Puesto:')),
                ('type_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typeemployee', verbose_name='Tipo de empleado:')),
                ('type_payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typepayroll', verbose_name='Tipo de nómina:')),
                ('deduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.deductioncatalog', verbose_name='Deducción:')),
            ],
            options={
                'unique_together': {('category', 'type_employee', 'type_payroll')},
            },
        ),
        migrations.CreateModel(
            name='BiweeklyPerceptionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perception_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor de la percepción:')),
                ('deduction_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor de la Deducción:')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.category', verbose_name='Puesto:')),
                ('type_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typeemployee', verbose_name='Tipo de empleado:')),
                ('type_payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typepayroll', verbose_name='Tipo de nómina:')),
                ('deduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.deductioncatalog', verbose_name='Deducción:')),
                ('perception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.perceptioncatalog', verbose_name='Percepción:')),
            ],
            options={
                'unique_together': {('category', 'type_employee', 'type_payroll')},
            },
        ),
    ]
