# Generated by Django 5.1.2 on 2025-05-07 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0003_alter_employmentdata_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentdata',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Salario:'),
        ),
        migrations.AddField(
            model_name='employmentdata',
            name='type_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typeemployee', verbose_name='Tipo de empleado:'),
        ),
        migrations.AddField(
            model_name='employmentdata',
            name='type_payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typepayroll', verbose_name='Tipo de nómina:'),
        ),
    ]
