# Generated by Django 5.1.2 on 2025-07-25 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0004_alter_category_id_alter_categoryconcept_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAdjustment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.concept')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='a_payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Fecha de inicio del periodo:')),
                ('end_date', models.DateField(verbose_name='Fecha de fin del periodo:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'ordering': ['start_date'],
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.RemoveField(
            model_name='employeeconcept',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='employeeconcept',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.AlterField(
            model_name='employeecategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='EmployeeConcept',
        ),
    ]
