# Generated by Django 5.1.2 on 2025-05-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0004_employmentdata_salary_employmentdata_type_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentdata',
            name='salary',
        ),
        migrations.AddField(
            model_name='employmentdata',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Salario total:'),
        ),
    ]
