# Generated by Django 5.1.2 on 2025-04-30 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0004_deductioncatalog_perceptioncatalog_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='biweeklyperceptionschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='biweeklyperceptionschedule',
            name='category',
        ),
        migrations.RemoveField(
            model_name='biweeklyperceptionschedule',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='biweeklyperceptionschedule',
            name='perception',
        ),
        migrations.RemoveField(
            model_name='biweeklyperceptionschedule',
            name='type_employee',
        ),
        migrations.RemoveField(
            model_name='biweeklyperceptionschedule',
            name='type_payroll',
        ),
        migrations.AlterUniqueTogether(
            name='biweeklysalaryschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='biweeklysalaryschedule',
            name='category',
        ),
        migrations.RemoveField(
            model_name='biweeklysalaryschedule',
            name='type_employee',
        ),
        migrations.RemoveField(
            model_name='biweeklysalaryschedule',
            name='type_payroll',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='testpayroll',
            name='type_employee',
        ),
        migrations.RemoveField(
            model_name='testpayroll',
            name='type_payroll',
        ),
        migrations.CreateModel(
            name='CategoryTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typeemployee', verbose_name='Tipo de empleado:')),
                ('type_payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typepayroll', verbose_name='Tipo de nómina:')),
            ],
        ),
        migrations.AddField(
            model_name='testpayroll',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.categorytab', verbose_name='Categoría del puesto:'),
        ),
        migrations.AlterField(
            model_name='employmentdata',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.categorytab', verbose_name='Categoría de empleado:'),
        ),
        migrations.CreateModel(
            name='DeductionTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor de la Deducción:')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.categorytab', verbose_name='Categoría del Puesto:')),
                ('deduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.deductioncatalog', verbose_name='Deducción:')),
            ],
        ),
        migrations.CreateModel(
            name='PerceptionTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perception_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor de la percepción:')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.categorytab', verbose_name='Categoría del Puesto:')),
                ('perception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.perceptioncatalog', verbose_name='Percepción:')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, unique=True, verbose_name='cve')),
                ('name', models.CharField(unique=True, verbose_name='Puesto:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción:')),
            ],
            options={
                'unique_together': {('key', 'name')},
            },
        ),
        migrations.AddField(
            model_name='categorytab',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.position', verbose_name='Puesto:'),
        ),
        migrations.AddField(
            model_name='employmentdata',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_payroll.position', verbose_name='Puesto:'),
        ),
        migrations.DeleteModel(
            name='BiweeklyDeductionSchedule',
        ),
        migrations.DeleteModel(
            name='BiweeklyPerceptionSchedule',
        ),
        migrations.DeleteModel(
            name='BiweeklySalarySchedule',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterUniqueTogether(
            name='categorytab',
            unique_together={('position', 'type_employee', 'type_payroll')},
        ),
    ]
