# Generated by Django 5.1.2 on 2025-07-25 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0005_employeeadjustment_payrollperiod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_payroll.category'),
        ),
    ]
