# Generated by Django 5.1.2 on 2025-05-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0005_alter_biweeklyperceptionschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del atributo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('type', models.CharField(choices=[('P', 'Percepción'), ('D', 'Deducción')], max_length=1, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='a_payroll.attributecatalog')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='a_payroll.categorytab')),
            ],
            options={
                'ordering': ('attribute__type', 'attribute__name'),
                'unique_together': {('category', 'attribute')},
            },
        ),
    ]
