# Generated by Django 5.1.2 on 2025-05-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0005_remove_employmentdata_salary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmentdata',
            old_name='chek_in_time',
            new_name='check_in_time',
        ),
        migrations.RenameField(
            model_name='employmentdata',
            old_name='chek_out_time',
            new_name='check_out_time',
        ),
    ]
