# Generated by Django 5.1.2 on 2025-05-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0006_rename_chek_in_time_employmentdata_check_in_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmploymentData',
            new_name='EmployeeJobData',
        ),
    ]
