# Generated by Django 5.1.2 on 2025-08-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0006_alter_employeecategory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollperiod',
            options={'ordering': ['start_date', 'end_date']},
        ),
        migrations.AddField(
            model_name='concept',
            name='order_report',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
