# Generated by Django 5.1.2 on 2025-05-05 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0006_attributecatalog_categoryattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perceptiontab',
            name='category',
        ),
        migrations.RemoveField(
            model_name='perceptiontab',
            name='perception',
        ),
        migrations.RemoveField(
            model_name='employmentdata',
            name='category',
        ),
        migrations.CreateModel(
            name='EmployeeIncome',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='income_concepts', serialize=False, to='a_payroll.employee')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_concepts', to='a_payroll.attributecatalog')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_category', to='a_payroll.categorytab')),
            ],
        ),
        migrations.DeleteModel(
            name='DeductionTab',
        ),
        migrations.DeleteModel(
            name='PerceptionTab',
        ),
    ]
