# Generated by Django 5.1.2 on 2025-05-11 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0007_rename_employmentdata_employeejobdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeejobdata',
            name='type_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typeemployee', verbose_name='Tipo de empleado:'),
        ),
        migrations.AlterField(
            model_name='employeejobdata',
            name='type_payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.typepayroll', verbose_name='Tipo de nómina:'),
        ),
    ]
