# Generated by Django 5.1.2 on 2025-08-22 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_payroll', '0007_alter_payrollperiod_options_concept_order_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeadjustment',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor:'),
        ),
        migrations.CreateModel(
            name='PayrollTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor:')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_payroll.concept')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts_payrolls_test', to='a_payroll.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_payroll.payrollperiod')),
            ],
        ),
    ]
