# Generated by Django 5.1.2 on 2025-05-30 12:12

import apps.a_police.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Acta de nacimiento'), (2, 'Curriculum'), (3, 'CURP'), (4, 'RFC'), (5, 'IMSS'), (6, 'INE'), (7, 'Licencia de manejo'), (8, 'Cartilla de servicio militar'), (9, 'Certificado de estudios'), (10, 'Comprobante de domicilio'), (11, 'Fotografia de frente')], verbose_name='Nombre del documento')),
                ('document', models.FileField(help_text='Solo archivos PDF menores a 5MB', upload_to=apps.a_police.models.user_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Documento')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['type'],
                'unique_together': {('user', 'type')},
            },
        ),
    ]
