# Generated by Django 5.1.2 on 2025-01-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_dependencetransparency_alter_transparency_dependence"),
    ]

    operations = [
        migrations.AddField(
            model_name="transparency",
            name="name",
            field=models.CharField(
                default="Default name", verbose_name="Nombre del archivo"
            ),
            preserve_default=False,
        ),
    ]
