# Generated by Django 5.1.2 on 2025-04-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_gazette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazette',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True, verbose_name='Mes'),
        ),
    ]
