# Generated by Django 5.1.2 on 2025-05-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_gazette_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogroup',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Nombre del grupo'),
        ),
        migrations.AlterField(
            model_name='infosubgroup',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Nombre de la categoría o subgrupo'),
        ),
        migrations.AlterUniqueTogether(
            name='infosubgroup',
            unique_together={('group', 'name')},
        ),
    ]
