# Generated by Django 5.1.2 on 2025-09-01 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_infogroup_name_alter_infosubgroup_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_cotaipec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='website.menu_cotaipec')),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
