# Generated by Django 5.1.2 on 2025-09-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_menu_cotaipec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_cotaipec',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='transparency/cotaipec/documents/'),
        ),
    ]
