# Generated by Django 5.1.2 on 2025-09-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_menu_cotaipec_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_cotaipec',
            name='nombre',
            field=models.TextField(verbose_name='Texto:'),
        ),
    ]
