# Generated by Django 5.1.2 on 2025-11-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_menu_cotaipec_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infogroup',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='infogroup',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
