# Generated by Django 5.1.2 on 2025-11-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_infogroup_options_infogroup_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogroup',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
