# Generated by Django 5.1.2 on 2025-11-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_infogroup_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogroup',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
