# Generated by Django 5.1.2 on 2025-11-13 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_infogroup_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del Documento/Archivo:'),
        ),
        migrations.AlterField(
            model_name='infogroup',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Nombre de la Categoría/Grupo:'),
        ),
        migrations.AlterField(
            model_name='infosubgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgrupos', to='website.infogroup', verbose_name='Categoría o Grupo:'),
        ),
    ]
