# Generated by Django 5.1.2 on 2025-11-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_accounting_name_alter_infogroup_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosubgroup',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
