# Generated by Django 5.1.2 on 2025-11-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_infosubgroup_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounting',
            options={'ordering': ['year', 'group', 'subgroup', 'quarter']},
        ),
        migrations.AlterModelOptions(
            name='infosubgroup',
            options={'ordering': ['group', 'order']},
        ),
        migrations.AlterField(
            model_name='infosubgroup',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Nombre de la subcategoría o subgrupo'),
        ),
        migrations.AlterUniqueTogether(
            name='accounting',
            unique_together={('group', 'name')},
        ),
    ]
