# Generated by Django 5.1.2 on 2025-11-14 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_accounting_options_alter_infosubgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_smapae', to='website.infosubgroup'),
        ),
    ]
