# Generated by Django 5.1.2 on 2025-11-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_accounting_subgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounting',
            options={'ordering': ['quarter']},
        ),
        migrations.AddField(
            model_name='accounting',
            name='periodo_publicacion',
            field=models.CharField(blank=True, choices=[('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], null=True, verbose_name='Periodo de publicación:'),
        ),
    ]
