# Generated by Django 5.1.2 on 2025-11-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_accounting_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounting',
            old_name='periodo_publicacion',
            new_name='periodo',
        ),
    ]
