# Generated by Django 5.1.2 on 2025-11-18 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_rename_periodo_publicacion_accounting_periodo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sevac_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='Año')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Nombre de la Categoría/Grupo:')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='accounting',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='dependence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.dependence', verbose_name='Dirección/Dependencia'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='website.infogroup'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_smapae', to='website.infosubgroup'),
        ),
        migrations.AlterField(
            model_name='infosubgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subgrupos', to='website.infogroup', verbose_name='Categoría o Grupo:'),
        ),
        migrations.CreateModel(
            name='sevac_subcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Nombre de la subcategoría o subgrupo')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='website.sevac_category', verbose_name='Categoría o Grupo:')),
            ],
            options={
                'ordering': ['category', 'order'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='sevac_document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=5, verbose_name='Año')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Documento/Archivo:')),
                ('document', models.FileField(upload_to='sevac/document/', verbose_name='Documento')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='website.sevac_category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_smapae', to='website.sevac_subcategory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
