# Generated by Django 5.1.2 on 2025-11-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_sevac_category_alter_accounting_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sevac_subcategory',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='sevac_document',
            name='year',
            field=models.IntegerField(verbose_name='Año'),
        ),
    ]
