# Generated by Django 5.1.2 on 2025-11-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_sevac_subcategory_year_alter_sevac_document_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='semestre',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Primer'), (2, 'Segundo')], null=True, verbose_name='Semestre:'),
        ),
    ]
