# Generated by Django 5.1.2 on 2025-02-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='RFC')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre:')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Primer apellido:')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo apellido:')),
                ('street', models.CharField(max_length=200, verbose_name='Calle:')),
                ('colony', models.CharField(blank=True, null=True, verbose_name='Colonia:')),
                ('locality', models.CharField(blank=True, null=True, verbose_name='Localidad:')),
                ('reference', models.CharField(blank=True, null=True, verbose_name='Referencia:')),
                ('municipality', models.CharField(blank=True, null=True, verbose_name='Municipio:')),
                ('state', models.CharField(blank=True, null=True, verbose_name='Estado:')),
                ('country', models.CharField(blank=True, null=True, verbose_name='Pais:')),
                ('cellphone', models.CharField(blank=True, null=True, unique=True, verbose_name='Celular:')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico:')),
                ('postal_code', models.CharField(blank=True, null=True, verbose_name='Municipio:')),
                ('person_type', models.IntegerField(choices=[(1, 'Persona física'), (2, 'Persona moral')], verbose_name='Tipo de contributente:')),
            ],
        ),
    ]
