# Generated by Django 5.1.2 on 2025-04-21 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Banco:')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(unique=True, verbose_name='Cuenta contable:')),
                ('name', models.CharField(unique=True, verbose_name='Nombre de la Categoría/Ramo:')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True, verbose_name='Nombre:')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Forma de pago:')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Estatus del pago:')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.BigIntegerField(unique=True, verbose_name='Número de cuenta:')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_income.bank', verbose_name='Banco:')),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(unique=True, verbose_name='Cuenta contable:')),
                ('name', models.CharField(unique=True, verbose_name='Nombre del concepto:')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_income.bankaccount', verbose_name='Cuenta bancaria:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='a_income.category', verbose_name='Categoría/Ramo:')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person_type', models.IntegerField(choices=[(1, 'Persona física'), (2, 'Persona moral')], verbose_name='Tipo de contributente:')),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='RFC')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre:')),
                ('paternalsurname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Primer apellido:')),
                ('maternalsurname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo apellido:')),
                ('country', models.CharField(blank=True, null=True, verbose_name='Pais:')),
                ('state', models.CharField(blank=True, null=True, verbose_name='Estado:')),
                ('municipality', models.CharField(blank=True, null=True, verbose_name='Municipio:')),
                ('colony', models.CharField(blank=True, null=True, verbose_name='Colonia:')),
                ('postal_code', models.CharField(blank=True, null=True, verbose_name='Código portal:')),
                ('street', models.CharField(max_length=200, verbose_name='Calle:')),
                ('no_ext', models.CharField(blank=True, max_length=10, null=True, verbose_name='No.Ext:')),
                ('no_int', models.CharField(blank=True, max_length=10, null=True, verbose_name='No.Int:')),
                ('reference', models.CharField(blank=True, null=True, verbose_name='Referencia:')),
                ('cellphone', models.CharField(blank=True, null=True, unique=True, verbose_name='Celular:')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico:')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailPay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad:')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Descripción:')),
                ('unit_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_income.concept', verbose_name='Concepto')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='income_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_type', to='a_income.incometype', verbose_name='Tipo de ingreso:'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Metodo de pago:')),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_income.paymentform')),
            ],
            options={
                'unique_together': {('payment_form', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice', models.BooleanField(default=False, verbose_name='Requiere factura:')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_details', models.JSONField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_in_payments', to='a_income.concept', verbose_name='Concepto:')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_income.customer', verbose_name='Cliente:')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('pay_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_income.paymentform')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_income.paymentmethod', verbose_name='Metodo de pago:')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_income.paymentstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(unique=True, verbose_name='Cuenta contable:')),
                ('name', models.CharField(unique=True, verbose_name='Nombre de la subcategoría:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_category', to='a_income.category', verbose_name='Categoría/Ramo:')),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='a_income.subcategory', verbose_name='Subcategoría:'),
        ),
        migrations.AlterUniqueTogether(
            name='concept',
            unique_together={('category', 'subcategory')},
        ),
    ]
