# Generated by Django 5.1.2 on 2025-04-21 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='income_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_type', to='a_income.incometype', verbose_name='Tipo de ingreso:'),
        ),
        migrations.AlterField(
            model_name='incometype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
