# Generated by Django 5.1.2 on 2025-11-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_income', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentform',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paymentform',
            name='fixed_fee',
        ),
        migrations.RemoveField(
            model_name='paymentform',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='paymentform',
            name='processing_fee_percentage',
        ),
        migrations.RemoveField(
            model_name='paymentform',
            name='requires_online',
        ),
    ]
