# Generated by Django 5.1.2 on 2025-02-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_income', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='locality',
        ),
        migrations.AddField(
            model_name='customer',
            name='no_ext',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='No.Ext:'),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_int',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='No.Int:'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, null=True, verbose_name='Código portal:'),
        ),
    ]
