# Generated by Django 5.1.2 on 2025-11-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_income', '0002_remove_paymentform_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='factor_type',
            field=models.CharField(blank=True, choices=[('Tasa', 'Tasa'), ('Cuota', 'Cuota'), ('Exento', 'Exento')], max_length=10, null=True, verbose_name='Tipo de Factor'),
        ),
        migrations.AddField(
            model_name='tax',
            name='sat_tax_code',
            field=models.CharField(blank=True, choices=[('001', 'ISR'), ('002', 'IVA'), ('003', 'IEPS')], max_length=3, null=True, verbose_name='Código SAT'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='IsFederalTax',
            field=models.BooleanField(default=True, verbose_name='Es Impuesto Federal:'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='IsQuota',
            field=models.BooleanField(default=False, verbose_name='Es cuota:'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='IsRetention',
            field=models.BooleanField(default=False, verbose_name='Es Retenido:'),
        ),
    ]
