# Generated by Django 5.1.2 on 2025-04-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_income', '0002_incometype_description_alter_category_income_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, null=True, verbose_name='Código postal:'),
        ),
    ]
