# Generated by Django 5.1.2 on 2025-02-18 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_income', '0002_remove_customer_locality_customer_no_ext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.IntegerField(verbose_name='Número de cuenta:')),
                ('name', models.CharField(verbose_name='Nombre de la Categoría/Ramo:')),
                ('category_type', models.IntegerField(choices=[(1, 'Caja'), (2, 'Federal')], verbose_name='Tipo:')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.IntegerField(verbose_name='Número de cuenta:')),
                ('name', models.CharField(verbose_name='Nombre de la subcategoría:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_income.category', verbose_name='Categoría/Ramo:')),
            ],
        ),
        migrations.CreateModel(
            name='Concep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.IntegerField(verbose_name='Número de cuenta:')),
                ('name', models.CharField(verbose_name='Nombre del concepto:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_income.category', verbose_name='Categoría/Ramo:')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_income.subcategory', verbose_name='Subcategoría:')),
            ],
        ),
    ]
