# Generated by Django 5.1.2 on 2025-02-19 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_income', '0003_category_subcategory_concep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(verbose_name='Banco:')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.BigIntegerField(verbose_name='Número de cuenta:')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_income.bank', verbose_name='Banco:')),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.IntegerField(verbose_name='Número de cuenta:')),
                ('name', models.CharField(verbose_name='Nombre del concepto:')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_income.bankaccount', verbose_name='Cuenta bancaria:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_income.category', verbose_name='Categoría/Ramo:')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_income.subcategory', verbose_name='Subcategoría:')),
            ],
        ),
        migrations.DeleteModel(
            name='Concep',
        ),
    ]
