# Generated by Django 5.1.2 on 2025-11-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_income', '0003_tax_factor_type_tax_sat_tax_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10, verbose_name='Tarifa:'),
        ),
    ]
