# Generated by Django 5.1.2 on 2025-11-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_income', '0004_alter_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cfdi_cancellation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cfdi_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de timbrado'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cfdi_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cfdi/pdf/%Y/%m/', verbose_name='PDF del CFDI'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cfdi_status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado del CFDI'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cfdi_uuid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='UUID del CFDI'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cfdi_xml',
            field=models.FileField(blank=True, null=True, upload_to='cfdi/xml/%Y/%m/', verbose_name='XML del CFDI'),
        ),
    ]
