# Generated by Django 5.1.2 on 2025-02-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_income', '0004_bank_bankaccount_concept_delete_concep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[(1, 'Caja'), (2, 'Federal')], verbose_name='Tipo:'),
        ),
    ]
