# Generated by Django 5.1.2 on 2025-02-19 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_income', '0005_alter_category_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(verbose_name='Nombre:')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.AddField(
            model_name='category',
            name='income_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a_income.incometype', verbose_name='Tipo de ingreso:'),
            preserve_default=False,
        ),
    ]
