# Generated by Django 5.1.2 on 2025-11-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_income', '0005_invoice_cfdi_cancellation_date_invoice_cfdi_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cfdi_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='Id del CFDI'),
        ),
    ]
