# Generated by Django 5.1.2 on 2025-02-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_income', '0006_incometype_remove_category_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='account_number',
            field=models.CharField(verbose_name='Número de cuenta:'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='account_number',
            field=models.CharField(verbose_name='Número de cuenta:'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='account_number',
            field=models.CharField(verbose_name='Número de cuenta:'),
        ),
    ]
