# Generated by Django 5.1.2 on 2025-02-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_income', '0008_alter_bank_name_alter_bankaccount_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='second_name',
            new_name='maternalsurname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='paternalsurname',
        ),
        migrations.AlterField(
            model_name='category',
            name='account_number',
            field=models.CharField(unique=True, verbose_name='Cuenta contable:'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='account_number',
            field=models.CharField(unique=True, verbose_name='Cuenta contable:'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='account_number',
            field=models.CharField(unique=True, verbose_name='Cuenta contable:'),
        ),
    ]
